### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by Spideynati** [xnl-h4ck3r/GAP-Burp-Extension#6]
Using burp version 2022.12.5 tried previous versions also 
This is the error I'm getting

"doEverything 1
AttributeError("'NoneType' object has no attribute 'toString'",)"

After sending target to GAP

**Comment by xnl-h4ck3r** [comment]
Hi. I'm not sure why it happens, but someone else had this issue and they said it was resolved by moving the cloned folder to a different directory. Maybe try changing the folder to make sure it has no spaces, and not non ASCII characters, and see if that fixes the problem?
Thanks
Xnl

**Comment by Spideynati** [comment]
Hey, I tried what you mentioned above it didn't work for me but GAP is working in burp version 2022.8.5 I tried changing the jython version and also tried it on 3-4 targets on latest version, I'm using Kali Linux. 
This extension is so awesome though I must say,
Thank you!

**Comment by xnl-h4ck3r** [comment]
Hey. Sorry, I thought that errror was happening when you tried loading the extension itself. Is it loading okay, but when you try to run for a target you get that error? Does it throw the same error for every target you try? Can you give me an example of a target you are looking at?
Also, I'm not sure if this causes any problems, but could you check if the "Auto save output to directory" contains any spaces or non ASCII characters?

**Comment by Spideynati** [comment]
The error occurs when I'm sending my target to GAP, save output directory is "/home/username/Documents/" target i used:
www.caffeine.tv, www.tinder.com(thier subdomains as well), also tried other like google.com and so its gives the same attribute error in newer versions after 2022.8.5

**Comment by xnl-h4ck3r** [comment]
Just to clarify, you are right clicking on a target on the "Target -> Site map" pane, and selecting "Extensions" and then "GAP"??
To have that speciifc error, it must mean tha the Burp API is returning a None type for "getSelectedMessages" in the Interface IContextMenuInvocation. But I can't see how that is possible, and I can't reproduce it :(
Do you have any problems with any other extensions that you access in the same way through the Target Site map?

**Comment by Spideynati** [comment]
Sorry for late reply,
Actually yeah I doing exactly like you told like target>site map then selecting GAP in extension tab no matter what target i use, I even did fresh installation and used it without any other extensions still got that error in Kali linux.
But,
When i used it with Windows it worked just fine in the latest version with other extensions and my previous file not sure why it worked there and not in kali though
Just to clarify I'm attaching the ss of the error I'm getting in Kali after sending target to GAP
![burpgaperror.png](https://user-images.githubusercontent.com/86477155/210715417-c89cdade-ea18-43bd-942f-0cb98cbe6bdf.png)

**Comment by Spideynati** [comment]
Hey, @xnl-h4ck3r the whole problem solved by Changing java-jdk version to 19 it was 17 before in kali linux.
You can close the issue.
Thanks once again for such an amazing tool.

**Comment by xnl-h4ck3r** [comment]
Hey @Spideynati thanks for letting me know! I'm glad you figured it out :)
